server:
  port: 9006

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5  #\u4FA6\u542C\u5668\u7684\u6700\u5C0F\u7EBF\u7A0B\u6570
        max-concurrency: 10  #\u4FA6\u542C\u5668\u7684\u6700\u5927\u7EBF\u7A0B\u6570
        acknowledge-mode: manual # auth:\u81EA\u52A8\u7B7E\u6536 manual:\u624B\u52A8\u7B7E\u6536  NONE:\u4E0D\u7B7E\u6536 \u63A8\u8350\u624B\u52A8\u7B7E\u6536
        prefetch: 2


