server:
  port: 9002
  servlet:
    context-path: /sc

logging:
  level:
    root: info

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8   # 设置全局时区
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa_test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
      #create：每次运行程序时，都会重新创建表，故而数据会丢失
      #create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
    #update：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
    #validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
    #none: 禁用 DDL 处理
    hibernate:
      ddl-auto: update


