spring:
  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jpa_multi_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jpa_multi_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
