multitenancy:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      maxPoolSize:  10
      idleTimeout:  300000
      minIdle:  10
      poolName: master-database-connection-pool

spring:
  mail:
    #    host: smtp.163.com
    #    username: wangyu_test2021@163.com
    #    password: OVNHDEVWSPCFTSDP
    #    default-encoding: UTF-8
    host: smtp.gmail.com
    username: wangyuamy102@gmail.com
    password: Gaia@2021
    default-encoding: UTF-8
    protocol: smtp
    # port: 587
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  messages:
    basename: i18n.messages
    encoding: UTF-8

  redis:
    host: 127.0.0.1
    #host: 172.16.0.67
    port: 6379
    database: 0
    #password: ics12345
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）默认8
        max-wait: -1ms  # 连接池最大阻塞等待时间
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接


mail:
  from: ${spring.mail.username}
  to: wangyuamy102@gmail.com



token:
  secret: helloworld
  expireTime: 1800