server:
  port: 8081
  servlet:
    context-path: /girl
logging:
  level:
    root: info

spring:
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    #轮询时间，默认为-1，不轮询
    timeBetweenEvictionRunsMillies: 30000
    #空闲时是否检查连接池中的连接是否有效，默认为false
    testWhileIdle: true
    #获取连接时是否检测是否有效，默认false
    testOnBorrow: true


  profiles:
    active: @profiles.active@