server:
  port: 9005


spring:
  application:
    name: mongodb
  data:
    mongodb:
     uri: mongodb://admin:123456@localhost:27017/?authSource=admin
     database: loser




  # uri: mongodb://账号:密码@x.x.x.x:端口/?authSource=admin
  # database: 数据库名




