server:
  port: 9009


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa-crud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
    hikari:
      #最大连接数
      maximum-pool-size: 20
      #连接超时毫秒
      connection-timeout: 60000
      #空闲的连接的生命时长毫秒
      idle-timeout: 60000
      #连接的生命时长毫秒
      max-lifetime: 60000
      #验证连接有效性毫秒
      validation-timeout: 3000
      #登录超时毫秒
      login-timeout: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    # open-in-view: true
  messages:
    basename: i18n.messages
    encoding: UTF-8