server:
  port: 9004
  servlet:
    context-path: /mp

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8   # 设置全局时区
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#  redis:
#    database: 0
#    password: HwCt@2020
#    cluster:
#      max-redirects: 3 # 获取失败 最大重定向次数
#      nodes: 121.37.158.84:9001,121.37.158.84:9002,121.36.197.8:9001,121.36.197.8:9002,121.36.248.221:9001,121.36.248.221:9002
#    lettuce:
#      pool:
#        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
#        min-idle: 5 # 连接池中的最小空闲连接
#        max-idle: 100 # 连接池中的最大空闲连接
#        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 1000


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    # 这个配置会将执行的sql打印出来，在开发和测试的时候使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #mapper-locations: classpath*:mapper/user/*.xml
  type-enums-package: com.example.mybatisplus.commons.enums
  type-aliases-package: com.example.mybatisplus.entity



