server:
  port: 9005
  servlet:
    context-path: /demo

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8   # \u8BBE\u7F6E\u5168\u5C40\u65F6\u533A
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/mybatis_multi_tenant?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

